apiVersion: v2
appVersion: v0.13.0
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.6
description: A Helm chart for Quality Trace
home: https://github.com/intelops/quality-trace
name: quality-trace
sources:
- https://github.com/intelops/quality-trace/tree/main/charts
type: application
version: 1.0.2
